### ISSUE TITLE
Add support for mongodb+srv connection strings

### ISSUE THREAD

**Issue by denizdogan** [erfanium/atlas_sdk#27]
Would be nice to have this, since it's so common.

**Comment by erfanium** [comment]
I don't think we could extract the required fields from a mongodb+srv connection string.
e.g.: dataSource, appId, apiKey

do you have any suggestions?

**Comment by denizdogan** [comment]
@erfanium Why not? I'm not super-familiar with Atlas myself, but I think I regularly connect to an Atlas cluster at work. 😆 

Looking at the [MongoDB documentation](https://www.mongodb.com/docs/atlas/tutorial/connect-to-your-cluster/#connect-to-your-atlas-cluster), it also looks like it should be possible:

```
// Replace the following with your Atlas connection string
const url = "mongodb+srv://<username>:<password>@<clusterName>.mongodb.net/?retryWrites=true&w=majority";
```

So I guess you somehow generate a connection string from the UI? I'm not sure.

**Comment by boywithkeyboard** [comment]
@denizdogan I think you're missing a point here. This library is for MongoDB Atlas' **Data API** (over HTTPS) and not for a regular MongoDB connection.

Your future request is impossible to implement...

**Comment by denizdogan** [comment]
@boywithkeyboard Hahah, that explains a lot :) Was trying to be helpful, but missed the mark by a mile! Sorry for the noise 👍
