### ISSUE TITLE
Bug in MongoDB DATA API, how to avoid it ?

### ISSUE THREAD

**Issue by UrielCh** [erfanium/atlas_sdk#28]
Hi,

Since I have added strict validation to my model, some of my requests failed where why are encoded as `application/ejson` but still works as `application/ejson` it's looks like the bug is in mongoDB Data API, but the project is not opensource ...

to bypass the issue the request must be encoded as JSON, not EJSON.

Is that possible to force encoding to JSON ?

**Comment by erfanium** [comment]
@UrielCh 
Hey!

You really should not use plain JSON over EJSON when working with MongoDB, because plain JSON bodies do not include type information. For example, when you send `{ _id: "507f191e810c19729de860ea" }` to the API, the server treats the `_id` value as a `string` instead of an `ObjectId`, which is completely incorrect.

Since you haven't provided any additional details about your project, I can't offer much help unless I am able to reproduce the problem myself.

**Comment by UrielCh** [comment]
for now, I just looking for a way to make one specific call to work.
I can provide you with the request that causes the bug.

**Comment by UrielCh** [comment]
## CURL request as EJSON
```bash
curl --location --request POST 'https://eu-central-1.aws.data.mongodb-api.com/app/data-xxxxxxxx/endpoint/data/v1/action/updateOne' \
--header 'Content-Type: application/ejson' \
--header 'Access-Control-Request-Headers: *' \
--header "api-key: 1234556789012345678901234567890234567890" \
--data-raw '{
    "collection":"account",
    "database":"academy",
    "dataSource":"Cluster0",
    "filter": {"_id":{"$oid":"6491f18560c497effb8be660"},"pending":"6491f18560c497effb8be65f","code":74},
    "update": {"$unset":{"pending":"","code":""},"$push":{"tokens":{"$each":["6491f18560c497effb8be65f"],"$slice":-10}}}
}'
```
> "Failed to update document: FunctionError: (DocumentValidationFailure) Plan executor error during findAndModify :: caused by :: Document failed validation"%      



## CURL request as JSON
```bash
curl --location --request POST 'https://eu-central-1.aws.data.mongodb-api.com/app/data-xxxxxxxx/endpoint/data/v1/action/updateOne' \
--header 'Content-Type: application/json' \
--header 'Access-Control-Request-Headers: *' \
--header "api-key: 1234556789012345678901234567890234567890" \
--data-raw '{
    "collection":"account",
    "database":"academy",
    "dataSource":"Cluster0",
    "filter": {"_id":"6491f18560c497effb8be660","pending":"6491f18560c497effb8be65f","code":74},
    "update": {"$unset":{"pending":"","code":""},"$push":{"tokens":{"$each":["6491f18560c497effb8be65f"],"$slice":-10}}}
}'
```
> {"matchedCount":0,"modifiedCount":0}%  


the JSON works not the EJSON

If I use EJSON I get an Error:

"\"Failed to update document: FunctionError: (DocumentValidationFailure) Plan executor error during findAndModify :: caused by :: Document failed validation\""

--------------

The request had works but return an error, my JSon request filter is not valid yet.

**Comment by erfanium** [comment]
i think your EJSON request body is incorrect. please wrap each object id with `ObjectId(hexstring)`. something like `{"_id":"6491f18560c497effb8be660" }` shouldn't be in you body without information about type. 
```sh
curl --location --request POST 'https://eu-central-1.aws.data.mongodb-api.com/app/data-xxxxxxxx/endpoint/data/v1/action/updateOne' \
--header 'Content-Type: application/ejson' \
--header 'Access-Control-Request-Headers: *' \
--header "api-key: 1234556789012345678901234567890234567890" \
--data-raw '{
    "collection":"account",
    "database":"academy",
    "dataSource":"Cluster0",
    "filter": {"_id": {"$oid":"6491f18560c497effb8be660"},"pending":{"$oid": "6491f18560c497effb8be65f"}, "code":74},
    "update": {"$unset":{"pending":"","code":""},"$push":{"tokens":{"$each":[{"$oid":"6491f18560c497effb8be65f"}],"$slice":-10}}}
}'
```

**Comment by UrielCh** [comment]
yep...
but now I have the same bug.

I can not use my request via the mongoDB DATA API.

using json cause the same issue....

**Comment by UrielCh** [comment]
I have to write my own mongoDB data API ...
thx for your time

**Comment by UrielCh** [comment]
I had disable all my `Validation`, my mongoDB data API will wait.

Can you just confirm for me, that mongoDB data API is mostly an external connection pool for mongo DB?

So it replaces TCP + keep alive connection by stateless HTTPS request
- add some nice logs.
- is greater for server-less pages.

or a NocoDB for MongoDB.  [see](https://github.com/nocodb/nocodb/issues/184)

**Comment by erfanium** [comment]
@UrielCh 
You can find the answers from MongoDB inc itself. this library aim's to be an type-safe SDK over MongoDB Data API. so I don't mind how the requests are being processed.

so if you think the generated request from this library is okay and the problem is from MongoDB itself, you can reach them

**Comment by UrielCh** [comment]
make sense.
