### ISSUE TITLE
By returning cursor.documents, instead of the plain cursor, there is a limit to how many documents can be returned

### ISSUE THREAD

**Issue by vrachev** [erfanium/atlas_sdk#31]
Source: https://github.com/erfanium/atlas_sdk/blob/b9ccb49a6593f2273e4317f4b51e165d516e6566/client.ts#L99-L115

I ran a find on a large collection and get 1000 documents back, even though I have more documents than that. This is because calling `cursor.documents` returns up to the batchSize in documents.

I think the API should instead return the plain cursor.

**Comment by erfanium** [comment]
@vrachev You mean MongoDB applies some sort of limit on the `find` method?

We don't have such a thing named `cursor` in Atlas Data API. as far as i know, cursors and streaming is only available to drivers

**Comment by vrachev** [comment]
> We don't have such a thing named cursor in Atlas Data API. as far as i know, cursors and streaming is only available to drivers

Sorry, you're right. I was looking at code from the x/mongo library which does use [return a cursor](https://github.com/denodrivers/mongo/blob/main/src/collection/commands/find.ts#L13-L29). 

> @vrachev You mean MongoDB applies some sort of limit on the find method?

Might be a bug with the atlas data API then. When I run `find()` I get back 1000 documents, when I run `aggregate()` I get all ~1500 docs. Same (empty) predicate both times.

**Comment by erfanium** [comment]
> Might be a bug with the atlas data API then. When I run find() I get back 1000 documents, when I run aggregate() I get all ~1500 docs. Same (empty) predicate both times.

Interesting, i didn't saw anything about this behavior in official docs

**Comment by erfanium** [comment]
closing this as we can't help about it
